### ISSUE TITLE
Documentation sphinx python

### ISSUE THREAD

**Issue by comorbidity** [Machine-Learning-for-Medical-Language/ctakes-client-py#13]
add documentation during "build" (sphinx python)

**Comment by mikix** [comment]
We had talked about sphinx or not - another big competitor is doxygen. Looks like fhirclient uses doxygen and is hosted on `docs.smarthealthit.org` while cnlpt uses sphinx and is hosted on `readthedocs.io`. So plenty of choices.

I'll investigate sphinx & readthedocs first.

**Comment by mikix** [comment]
I landed the manual sphinx build for now - without automatic pushing to readthedocs. That can happen later once we're comfy with it
