### ISSUE TITLE
expose ctakesclient tests accessible to user

### ISSUE THREAD

**Issue by comorbidity** [Machine-Learning-for-Medical-Language/ctakes-client-py#17]
example: 

`import ctakesclient `

Probably something nicer to read this, but currently
`ctakesclient.test.test_resources.LoadResource.COVID_SYMPTOMS`

**Comment by mikix** [comment]
We exposed `covid_symptoms()` and `umls_semantic_groups()` in https://github.com/Machine-Learning-for-Medical-Language/ctakes-client-py/commit/096e1cfd7811e117c2c51992333ff16917410323 -- I suspect that was the intent of this ticket and will close in a few days if that's right.
