### ISSUE TITLE
ctakesclient version should be easily by user 

### ISSUE THREAD

**Issue by comorbidity** [Machine-Learning-for-Medical-Language/ctakes-client-py#23]
`pyproject.toml` properties should be easily accesible like 

`ctakesclient.version.number` = 1.0.3 
`ctakesclient.version.url` = https://github.com/Machine-Learning-for-Medical-Language/ctakes-client-py

**Comment by mikix** [comment]
This is now fixed in 1.1.0: https://github.com/Machine-Learning-for-Medical-Language/ctakes-client-py/commit/d80a00de7a4668fd382920c4430ac788cdc7bd8a

```
import ctakesclient
print(ctakesclient.__version__)
```
