### ISSUE TITLE
duplicate concepts written to text2fhir coding statement 

### ISSUE THREAD

**Issue by comorbidity** [Machine-Learning-for-Medical-Language/ctakes-client-py#50]
example: `Appearance of rash consistent with erythema migrans. Given recent travel in Lyme disease endemic area, will treat with doxycycline 50mg BID x 2 weeks.`

includes response 
`    "medicationCodeableConcept": {
        "coding": [
            {
                "code": "10504007",
                "system": "http://snomed.info/sct"
            },
            {
                "code": "C0013090",
                "system": "http://terminology.hl7.org/CodeSystem/umls"
            },
            {
                "code": "3640",
                "system": "http://www.nlm.nih.gov/research/umls/rxnorm"
            },
            {
                "code": "C0013090",
                "system": "http://terminology.hl7.org/CodeSystem/umls"
            },
            {
                "code": "372478003",
                "system": "http://snomed.info/sct"
            },
            {
                "code": "C0013090",
                "system": "http://terminology.hl7.org/CodeSystem/umls"
            }
        ],
        "text": "doxycycline"
`

**Comment by comorbidity** [comment]
Note that this concept appears 3X

`                "code": "C0013090",
                "system": "http://terminology.hl7.org/CodeSystem/umls"
`

**Comment by mikix** [comment]
Looks like one way this can happen is when cTAKES returns mentions like:
```

            "conceptAttributes": [
                {
                    "code": "129265001",
                    "cui": "C1261322",
                    "codingScheme": "SNOMEDCT_US",
                    "tui": "T058"
                },
                {
                    "code": "386053000",
                    "cui": "C1261322",
                    "codingScheme": "SNOMEDCT_US",
                    "tui": "T058"
                }
            ],
```

So two different "Vocabulary Codes" for the same CUI. So I buy that cTAKES is doing the right thing and giving us both. But when we collapse that all into codeableConcepts with only CUIs (and ignore Vocabulary Codes), it's reasonable that we would remove duplicates.
